In [3]:
import csv
import pandas as pd

(25245, 17)

In [7]:
df = pd.read_csv('tmp/courses_old.csv', delimiter=';')
df.shape
df2 = df.drop_duplicates(subset=['CYEAR', 'CUID', 'CLNUM'], keep='last')

In [5]:
df2.head(5)

,CYEAR,CSN,CONUM,CLNUM,CNAME,CREDIT,CUID,CPERIOD,CTYPE,CPRO,CAPPLY,CTIME,CLIMIT,CCSTR,CNOTE,CWEBURL,CGPAURL
0,106_1,97001,PE1003,30,健康體適能,1.0,002 50010,半年,必帶,簡坤鐘,2,"三1,2(籃球A~E)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。1010中文系A合+1011中文系國際班A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=30
1,106_1,97002,PE1003,31,健康體適能,1.0,002 50010,半年,必帶,簡坤鐘,2,"三3,4(籃球A~E)",50,"健康體適能,本校修課人數上限：50人",初選不開放。2080地理系一合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=31
2,106_1,97003,PE1003,32,健康體適能,1.0,002 50010,半年,必帶,蔡秀華,2,"一8,9(籃球A~E)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。2030化學系A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=32
3,106_1,97004,PE1003,33,健康體適能,1.0,002 50010,半年,必帶,蔡秀華,2,"四1,2(籃球A~E)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。7040國企系A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=33
4,106_1,97005,PE1003,36,健康體適能,1.0,002 50010,半年,必帶,楊裕隆,2,"二6,7(足球場)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。7020會計系A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=36

In [6]:
cols = df2.columns.tolist()
cols[1], cols[6] = cols[6],  cols[1]
cols[2], cols[3] = cols[3], cols[2]
df2 = df2[cols]
df2.head(5)

,CYEAR,CUID,CLNUM,CONUM,CNAME,CREDIT,CSN,CPERIOD,CTYPE,CPRO,CAPPLY,CTIME,CLIMIT,CCSTR,CNOTE,CWEBURL,CGPAURL
0,106_1,002 50010,30,PE1003,健康體適能,1.0,97001,半年,必帶,簡坤鐘,2,"三1,2(籃球A~E)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。1010中文系A合+1011中文系國際班A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=30
1,106_1,002 50010,31,PE1003,健康體適能,1.0,97002,半年,必帶,簡坤鐘,2,"三3,4(籃球A~E)",50,"健康體適能,本校修課人數上限：50人",初選不開放。2080地理系一合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=31
2,106_1,002 50010,32,PE1003,健康體適能,1.0,97003,半年,必帶,蔡秀華,2,"一8,9(籃球A~E)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。2030化學系A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=32
3,106_1,002 50010,33,PE1003,健康體適能,1.0,97004,半年,必帶,蔡秀華,2,"四1,2(籃球A~E)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。7040國企系A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=33
4,106_1,002 50010,36,PE1003,健康體適能,1.0,97005,半年,必帶,楊裕隆,2,"二6,7(足球場)",50,"健康體適能 且 限學號雙號,本校修課人數上限：50人",初選不開放。7020會計系A合。,https://nol.ntu.edu.tw/nol/coursesearch/print_...,/history?&id=002+50010&cl=36

In [33]:
df2.to_csv('courses.csv',sep=';', index=False)

In [14]:
df = pd.read_csv('tmp/gpa_old.csv', delimiter=',')
df.shape
df2 = df.drop_duplicates(subset=['CYEAR', 'CUID', 'CLNUM'], keep='last')
df2.head(10)
df2.shape
df2.to_csv('gpa.csv',sep=',', index=False, float_format= '%.3f')